services:
  web:
    build: .
    container_name: WeatherApp
    volumes:
      - .:/api
      - static_volume:/api/staticfiles # Mount static files
      - media_volume:/api/media # Mount media files
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    command:
      ["gunicorn", "--bind", "0.0.0.0:8000", "Weather_App.wsgi:application"]
    networks:
      - Weather_App_network

  db:
    image: mysql:8.0
    container_name: mysql_db_weather_app
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - Weather_App_network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306" # Expose MySQL port

networks:
  Weather_App_network:

volumes:
  mysql_data:
  static_volume: # Persistent volume for static files
  media_volume: # Persistent volume for media files
