# Generated by Django 4.2.10 on 2025-04-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='annualdata',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='monthlydata',
            options={'ordering': ['year', 'month']},
        ),
        migrations.AlterModelOptions(
            name='seasonaldata',
            options={'ordering': ['year', 'season']},
        ),
    ]
